binutils_ver=2.23.2
binutils_=binutils-$(binutils_ver)
projects+=$(binutils_)
names+=binutils

$(eval $(call standard_x,$(binutils_)))

# config rules for binutils
build/$(arch)/$(binutils_)/._.config: source/$(binutils_)/._.patch
	(cd $(@D) && $(rootdir)/source/$(binutils_)/configure \
			--target=$(target) \
			--prefix=$(prefix) \
			$(sysroot) \
			--disable-nls \
			-v \
	) $(t) $@.log
	touch $@

compiler: binutils

# ENTRY
binutils: install-$(binutils_)
	@echo $@ done

