source/cfacter/.git: | source source/cfacter
	$(git) clone git@github.com:puppetlabs/cfacter.git source/cfacter/

build/$(arch)/cfacter/._.config: | source/cfacter/.git build/$(arch)/cfacter
	cd build/$(arch)/cfacter && env $(cmakepath) $(cmake) ../../../source/cfacter

facter-$(arch): build/$(arch)/cfacter/._.make

facter: facter-$(arch) 
